port='9999'
realm='zone name just for test'
key='secret key salt'
tokenLookup='header: Authorization, query: token, cookie: jwt'
tokenHeadName='Bearer'
loginPath='/login'
authPath='/auth'
refreshPath='/refresh_token'
testPath='/hello'
db_host     = "192.168.56.160"
db_port     = "5432"
db_user     = "gorm"
db_name   = "testdb"
db_password = "123456"
admin_name = 'user_d'
admin_pass = 'user_d'
casbin_config = './conf/auth.conf'
#casbin_policy = './conf/auth.csv'